<Estoque>:

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        TextInput:
            hint_text: 'Escreva...'
            font_size: 16
            size_hint_y: None
            height: 30

        ScrollView:
            BoxLayout:
                id: lista_produtos
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10