<Estoque>:
    FloatLayout:
        TextInput:
            size_hint: None, None
            height: self.minimum_height
            width: 500
            pos_hint: {"center_x": 0.5,"center_y": 0.9}

        Button:
            text: "Voltar"
            font_size: 18
            size_hint: None, None
            size: 100, 40
            pos_hint: {"center_x": 0.5, "y": 0.05}
            on_press: app.stop()